Repository lucyzhang04/326Project, pull requests merged in 2024-12, with the labels that each got.

#90 Implement Server-Side WebSocket -- #80
  backend/controller/SubmissionController.js
  backend/eventhub/EventHub.js
  backend/eventhub/Events.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
Labels: enhancement

#95 Quotes API Integration (see PR #94) - renamed branch
  front-end/index.html
Labels: duplicate, enhancement

#101 Quotes API Integration Comments
  front-end/index.html
Labels: documentation

#108 Debugging initial quote generation issue
  front-end/index.html
Labels: bug

#110 Debugged quote generation error
  front-end/index.html
  team/reports/mai-chi-le.md
Labels: bug

#118 Implementing client-side WebSocket -- #87
  backend/index.js
  backend/package-lock.json
  backend/package.json
  front-end/feed-script.js
  front-end/feed.html
  front-end/styles.css
Labels: bug, enhancement

#123 Feed UI -- Displays Current Day's Subs -- #122
  backend/controller/SubmissionController.js
  backend/model/SQLiteModel.js
  backend/routes/feed-routes.js
  front-end/feed-script.js
Labels: enhancement

#130 Quotes Database Integration
  backend/controller/QuotesController.js
  backend/model/SQLiteModel.js
Labels: enhancement

#135 Full Database Integration for Quotes
  backend/controller/QuotesController.js
  backend/index.js
  backend/model/SQLiteModel.js
  backend/routes/quote-routes.js
  front-end/index.html
  package-lock.json
  package.json
Labels: enhancement

#143 Adding Comments to Feed UI Work
  backend/controller/SubmissionController.js
  backend/eventhub/Events.js
  backend/index.js
  backend/model/SQLiteModel.js
  backend/routes/feed-routes.js
Labels: documentation

#148 Added Get Top Artists Summary Statistic
  backend/controller/SubmissionController.js
  backend/model/SQLiteModel.js
  backend/routes/trending-routes.js
  front-end/styles.css
  front-end/trending-script.js
  front-end/trending.html
Labels: enhancement

#156 Fix Sizing Issue on Feed Widgets #144
  front-end/feed-script.js
Labels: bug

#162 Added comments to explain quote-related code
  backend/index.js
  backend/model/SQLiteModel.js
  backend/routes/quote-routes.js
  front-end/index.html
Labels: documentation
